# Generated by Django 2.0.1 on 2018-01-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_links_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
