# Generated by Django 2.0.1 on 2018-01-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_link_root'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
