# Generated by Django 2.0.1 on 2018-01-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_delete_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
