# Generated by Django 2.0.1 on 2018-01-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_auto_20180116_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='service_type',
        ),
    ]
