# Generated by Django 2.0.1 on 2018-01-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_auto_20180116_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='picture',
            field=models.ImageField(blank=True, upload_to='staff_images'),
        ),
    ]
