# Generated by Django 2.0.1 on 2018-01-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_staff_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=models.ImageField(blank=True, upload_to='staff_images/'),
        ),
    ]
