# Generated by Django 2.0.1 on 2018-01-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0013_userprofile_liked_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='liked_services',
            field=models.ManyToManyField(blank=True, to='salon.Service', verbose_name='list of liked services'),
        ),
    ]
