# Generated by Django 2.0.1 on 2018-02-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0015_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='liked_services',
            field=models.ManyToManyField(blank=True, to='salon.Blog', verbose_name='list of liked blogs'),
        ),
    ]
