# Generated by Django 2.0.1 on 2018-02-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0016_auto_20180209_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_blogs',
            field=models.ManyToManyField(blank=True, to='salon.Blog', verbose_name='list of liked blogs'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_services',
            field=models.ManyToManyField(blank=True, to='salon.Service', verbose_name='list of liked services'),
        ),
    ]
